pipeline:
  clone:
    image: plugins/git
    depth: 1

  system-tests:
      image: jatitoam/docker-systemtests
      environment:
        - CLOUD_NAME=redcomponent
        - API_KEY=365447364384436
        - API_SECRET=Q94UM5kjZkZIrau8MIL93m0dN6U
        - GITHUB_TOKEN=4d92f9e8be0eddc0e54445ff45bf1ca5a846b609
        - ORGANIZATION=redCOMPONENT-COM
        - REPO=redSHOP
      volumes:
        - /root/drone/redshop-vendor:/vendor
      commands:
        - ls -la
        - whoami
        - pwd
        - ls -la
        - ./build/test-setup.sh
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_USER: joomla_ut
      MYSQL_PASSWORD: joomla_ut
      MYSQL_ROOT_PASSWORD: joomla_ut
      MYSQL_DATABASE: test_joomla