pipeline:
  clone:
    image: plugins/git
    depth: 1

  system-tests:
      image: docker
      volumes:
        - /root/drone/redshop-vendor:/vendor
      commands:
        - docker run --volumes-from redshop-composer-container jatitoam/docker-systemtests
        - whoami
        - pwd
        - ls -la
        - ./build/test-setup.sh
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_USER: joomla_ut
      MYSQL_PASSWORD: joomla_ut
      MYSQL_ROOT_PASSWORD: joomla_ut
      MYSQL_DATABASE: test_joomla