language:
  php

sudo:
  required

dist:
  trusty

node_js:
  - 8

php:
  - 5.6
  - 7.0

addons:
  chrome: stable

cache:
  apt: true
  directories:
    - "node_modules"
    - $HOME/.composer/cache/files

env:
  matrix:
      - ACCEPTANCE=false
      - ACCEPTANCE=acceptance/administrator/Category
      - ACCEPTANCE=acceptance/administrator/Configuration
      - ACCEPTANCE=acceptance/administrator/Country
      - ACCEPTANCE=acceptance/administrator/Coupon
      - ACCEPTANCE=acceptance/administrator/Currency
      - ACCEPTANCE=acceptance/administrator/Custome_Field
      - ACCEPTANCE=acceptance/administrator/Discount
      - ACCEPTANCE=acceptance/administrator/Discount_Product
      - ACCEPTANCE=acceptance/administrator/Giftcard
      - ACCEPTANCE=acceptance/administrator/Mail
      - ACCEPTANCE=acceptance/administrator/Mass_Discount
      - ACCEPTANCE=acceptance/administrator/Notices
      - ACCEPTANCE=acceptance/administrator/Order
      - ACCEPTANCE=acceptance/administrator/Price_Product
      - ACCEPTANCE=acceptance/administrator/Products
      - ACCEPTANCE=acceptance/administrator/Quotation
      - ACCEPTANCE=acceptance/administrator/Shipping
      - ACCEPTANCE=acceptance/administrator/Shopper_Group
      - ACCEPTANCE=acceptance/administrator/State
      - ACCEPTANCE=acceptance/administrator/Stock_Image
      - ACCEPTANCE=acceptance/administrator/StockRoom
      - ACCEPTANCE=acceptance/administrator/Supplier
      - ACCEPTANCE=acceptance/administrator/Tax_Rate
      - ACCEPTANCE=acceptance/administrator/Template
      - ACCEPTANCE=acceptance/administrator/Text
      - ACCEPTANCE=acceptance/administrator/User
      - ACCEPTANCE=acceptance/administrator/Voucher
      - ACCEPTANCE=acceptance/administrator/Wrapper
      - ACCEPTANCE=acceptance/integration

  global:
    - CLOUD_NAME=redcomponent
    - API_KEY=365447364384436
    - API_SECRET=Q94UM5kjZkZIrau8MIL93m0dN6U
    - GITHUB_TOKEN=4d92f9e8be0eddc0e54445ff45bf1ca5a846b609
    - ORGANIZATION=redCOMPONENT-COM
    - REPO=redSHOP

before_script:
  - ./.travis/setup.sh

script:
  - ./.travis/script.sh

after_script:
  - if [ $TRAVIS_PULL_REQUEST != "false" ]; then vendor/bin/robo send:screenshot-from-travis-to-github $CLOUD_NAME $API_KEY $API_SECRET $GITHUB_TOKEN $ORGANIZATION $REPO $TRAVIS_PULL_REQUEST; fi

notifications:
  slack:
    secure: XX4m+uA8suXodJS0SvLDqrWovNvx7bxiJwyebj3gA8JwSP2E3XsRJFxsAt5++GTOv1nmMCGIkXnovY44XoA8ErEVSseElCUtKOr3/sa6tCPDYl4Lz+Q4FxPxPJcz6glpwXyOc2tCMNaKWiFdWrDsHNucPjw9iN5N16+jIvYwrrQ=
